CREATE DATABASE IF NOT EXISTS `semaphore`;
CREATE USER IF NOT EXISTS 'semaphore'@'%' IDENTIFIED BY 'semaphorepass';
GRANT ALL PRIVILEGES ON `semaphore`.* TO 'semaphore'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS mc_airflow CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON mc_airflow.* TO 'mc-agent'@'%';
FLUSH PRIVILEGES;
