package com.innogrid.tabcloudit.o11ymanager.dto.host;

import com.innogrid.tabcloudit.o11ymanager.global.annotation.Base64DecodeField;
import com.innogrid.tabcloudit.o11ymanager.global.annotation.Base64EncodeField;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Config 내용 전달을 위한 DTO")
public class ConfigResponseDTO {
    @Schema(description = "Base64로 인코딩 된 설정 파일 내용", example = "W2dsb2JhbF90YWdzXQogIHV1aWQgPSAiOTRjM2U0MDItNTA0Mi00YzhlLTkyNDgtY2RmY2IxNDYyZGViIgogIHRhcmdldCA9ICJ2bSIKClthZ2VudF0KICBpbnRlcnZhbCA9ICI2MHMiCiAgbG9nZmlsZSA9ICIvY21wLWFnZW50L2xvZy90ZWxlZ3JhZi5sb2ciCiAgcm91bmRfaW50ZXJ2YWwgPSB0cnVlCiAgbWV0cmljX2JhdGNoX3NpemUgPSAxMDAwCiAgbWV0cmljX2J1ZmZlcl9saW1pdCA9IDIwMDAwCiAgY29sbGVjdGlvbl9qaXR0ZXIgPSAiMHMiCiAgZmx1c2hfaW50ZXJ2YWwgPSAiMTBzIgogIGZsdXNoX2ppdHRlciA9ICIwcyIKICBwcmVjaXNpb24gPSAiMHMiCgpbW2lucHV0cy5jcHVdXQogIHBlcmNwdSA9IHRydWUKICB0b3RhbGNwdSA9IHRydWUKICBjb2xsZWN0X2NwdV90aW1lID0gZmFsc2UKCltbaW5wdXRzLmRpc2tdXQogIGlnbm9yZV9mcyA9IFsidG1wZnMiLCAiZGV2dG1wZnMiLCAic3F1YXNoZnMiLCAib3ZlcmxheSIsICJuc2ZzIl0KCltbaW5wdXRzLmRpc2tpb11dCgpbW2lucHV0cy5tZW1dXQoKW1tpbnB1dHMubmV0XV0KCltbaW5wdXRzLnByb2Nlc3Nlc11dCgpbW2lucHV0cy5wcm9jc3RhdF1dCiAgcHJvcGVydGllcyA9IFsiY3B1IiwgImxpbWl0cyIsICJtZW1vcnkiLCAibW1hcCJdCiAgdGFnX3dpdGggPSBbInVzZXIiXQoKW1tpbnB1dHMucHJvY3N0YXQuZmlsdGVyXV0KICBuYW1lID0gIjk0YzNlNDAyLTUwNDItNGM4ZS05MjQ4LWNkZmNiMTQ2MmRlYiIKCltbaW5wdXRzLnN3YXBdXQoKW1tpbnB1dHMuc3lzdGVtXV0KCltbb3V0cHV0cy5pbmZsdXhkYl1dCiB1cmxzID0gWyJodHRwOi8vMTkyLjE2OC4xMTAuNDg6ODA4NiJdCiBkYXRhYmFzZSA9ICJjbXAiCiB1c2VybmFtZSA9ICJ0YWJjbG91ZGl0IgogcGFzc3dvcmQgPSAicXdlMTIxMiFRIgoKCg==")
    @Base64EncodeField
    @Base64DecodeField
    @NotBlank
    private String content;
}
