server {
    listen 3001;
    root /usr/share/nginx/html;
    index index.html;

    location /api/o11y/ {
        proxy_pass http://mc-observability-manager:18080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Origin "";
        proxy_hide_header Access-Control-Allow-Origin;
    }

    location /tumblebug/ {
        proxy_pass http://mc-infra-manager:1323;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization "Basic ZGVmYXVsdDpkZWZhdWx0";
        proxy_set_header Origin "";
        proxy_hide_header Access-Control-Allow-Origin;
    }

    location /spider/ {
        proxy_pass http://mc-infra-connector:1024;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization "Basic ZGVmYXVsdDpkZWZhdWx0";
        proxy_set_header Origin "";
    }

    location / {
        try_files $uri /index.html;
    }
}
