#!/usr/bin/env python3
"""
Merge Java and Python Swagger 2.0 specs into a single swagger.yaml.
- Java swagger: generated by springdoc (OpenAPI 3.0) and converted to Swagger 2.0
- Python swagger: extracted from FastAPI (OpenAPI 3.1) and converted to Swagger 2.0
"""

import json
import sys
from pathlib import Path

import yaml


def openapi3_to_swagger2(spec):
    """Convert OpenAPI 3.x spec dict to Swagger 2.0 spec dict."""
    swagger = {
        "swagger": "2.0",
        "info": spec.get("info", {}),
        "basePath": "/",
        "consumes": ["application/json"],
        "produces": ["application/json"],
    }

    servers = spec.get("servers", [])
    if servers:
        url = servers[0].get("url", "localhost")
        url = url.replace("https://", "").replace("http://", "")
        swagger["host"] = url

    paths = {}
    for path, methods in spec.get("paths", {}).items():
        converted_methods = {}
        for method, operation in methods.items():
            if method in ("get", "post", "put", "delete", "patch", "options", "head"):
                converted_methods[method] = convert_operation(operation)
        paths[path] = converted_methods
    swagger["paths"] = paths

    components = spec.get("components", {})
    schemas = components.get("schemas", {})
    if schemas:
        swagger["definitions"] = convert_schemas(schemas)

    return swagger


def convert_operation(op):
    """Convert a single OpenAPI 3.x operation to Swagger 2.0."""
    result = {}

    for key in ("tags", "summary", "description", "operationId"):
        if key in op:
            result[key] = op[key]

    result["produces"] = ["application/json"]

    params = []

    for p in op.get("parameters", []):
        param = {
            "name": p.get("name"),
            "in": p.get("in"),
            "description": p.get("description", ""),
            "required": p.get("required", False),
        }
        schema = p.get("schema", {})
        param["type"] = schema.get("type", "string")
        if "format" in schema:
            param["format"] = schema["format"]
        if "enum" in schema:
            param["enum"] = schema["enum"]
        if "default" in schema:
            param["default"] = schema["default"]
        params.append(param)

    request_body = op.get("requestBody")
    if request_body:
        content = request_body.get("content", {})
        for content_type, media in content.items():
            body_param = {
                "in": "body",
                "name": "",
                "required": request_body.get("required", False),
            }
            if "description" in request_body:
                body_param["description"] = request_body["description"]
            if "schema" in media:
                body_param["schema"] = convert_ref(media["schema"])
            params.append(body_param)
            result["consumes"] = [content_type]
            break

    if params:
        result["parameters"] = params

    responses = {}
    for code, resp in op.get("responses", {}).items():
        converted = {"description": ""}
        resp_content = resp.get("content")
        if resp_content:
            for ct, media in resp_content.items():
                if "schema" in media:
                    converted["schema"] = convert_ref(media["schema"])
                if "example" in media:
                    converted["examples"] = {ct: media["example"]}
                break
        responses[code] = converted
    result["responses"] = responses

    return result


def convert_ref(schema):
    """Recursively convert $ref from OpenAPI 3.x to Swagger 2.0 format."""
    if not isinstance(schema, dict):
        return schema

    result = {}
    for k, v in schema.items():
        if k == "$ref" and isinstance(v, str):
            result[k] = v.replace("#/components/schemas/", "#/definitions/")
        elif k in ("items", "additionalProperties"):
            result[k] = convert_ref(v)
        elif k == "properties" and isinstance(v, dict):
            result[k] = {pk: convert_ref(pv) for pk, pv in v.items()}
        elif k in ("allOf", "oneOf", "anyOf") and isinstance(v, list):
            result[k] = [convert_ref(item) for item in v]
        else:
            result[k] = v

    return result


def convert_schemas(schemas):
    """Convert all schemas, fixing $ref paths."""
    return {name: convert_ref(schema) for name, schema in schemas.items()}


def merge_swagger(java_spec, python_spec, info_override=None):
    """Merge Java and Python Swagger 2.0 specs."""
    merged = dict(java_spec)

    if info_override:
        merged["info"] = info_override

    # Merge paths: Python paths override Java for /api/o11y/insight/** paths
    java_paths = java_spec.get("paths", {})
    python_paths = python_spec.get("paths", {})

    merged_paths = dict(java_paths)
    for path, methods in python_paths.items():
        if path in merged_paths:
            # For insight paths, prefer Python spec (more detailed)
            if "/insight/" in path:
                merged_paths[path] = methods
        else:
            merged_paths[path] = methods
    merged["paths"] = merged_paths

    # Merge definitions
    java_defs = java_spec.get("definitions", {})
    python_defs = python_spec.get("definitions", {})

    merged_defs = dict(java_defs)
    for name, schema in python_defs.items():
        if name not in merged_defs:
            merged_defs[name] = schema
    merged["definitions"] = merged_defs

    return merged


def inject_examples(spec, examples):
    """Inject response examples into spec by matching operationId."""
    for path, methods in spec.get("paths", {}).items():
        for method, op in methods.items():
            op_id = op.get("operationId")
            if op_id and op_id in examples:
                for code, resp in op.get("responses", {}).items():
                    if "examples" not in resp:
                        resp["examples"] = {"application/json": examples[op_id]}


def main():
    project_root = Path(__file__).parent.parent
    swagger_dir = project_root / "swagger"

    java_swagger_path = swagger_dir / "java-swagger.yaml"
    python_swagger_path = swagger_dir / "python-swagger.yaml"
    output_path = swagger_dir / "swagger.yaml"

    if not java_swagger_path.exists():
        print(f"ERROR: {java_swagger_path} not found. Run Java swagger generation first.")
        sys.exit(1)

    with open(java_swagger_path) as f:
        java_spec = yaml.safe_load(f)

    if python_swagger_path.exists():
        with open(python_swagger_path) as f:
            python_spec = yaml.safe_load(f)
    else:
        print(f"WARNING: {python_swagger_path} not found. Using Java spec only.")
        python_spec = {"paths": {}, "definitions": {}}

    info_override = {
        "title": "MC-Observability API Documentation",
        "description": "API documentation for MC-Observability",
        "version": "0.4.3",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html",
        },
    }

    merged = merge_swagger(java_spec, python_spec, info_override)
    merged["host"] = "localhost:18080"

    # Inject response examples from pre-extracted file
    examples_path = Path(__file__).parent / "response_examples.yaml"
    if examples_path.exists():
        with open(examples_path) as f:
            response_examples = yaml.safe_load(f) or {}
        inject_examples(merged, response_examples)

    class QuotedStr(str):
        pass

    def quoted_str_representer(dumper, data):
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="'")

    yaml.add_representer(QuotedStr, quoted_str_representer)

    # Quote response codes (e.g., "200", "201")
    def quote_response_codes(paths):
        for path, methods in paths.items():
            for method, op in methods.items():
                if "responses" in op:
                    new_responses = {}
                    for code, resp in op["responses"].items():
                        new_responses[QuotedStr(str(code))] = resp
                    op["responses"] = new_responses

    # Set all response descriptions to empty string to match official swagger
    for path, methods in merged.get("paths", {}).items():
        for method, op in methods.items():
            if "responses" in op:
                for code, resp in op["responses"].items():
                    resp["description"] = ""
            # Set body parameter name to empty string
            for param in op.get("parameters", []):
                if param.get("in") == "body":
                    param["name"] = ""

    quote_response_codes(merged.get("paths", {}))

    # Ensure 'swagger' version is written as quoted string "2.0", not float
    merged["swagger"] = QuotedStr("2.0")

    with open(output_path, "w") as f:
        yaml.dump(
            merged,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=120,
        )

    print(f"Merged swagger written to {output_path}")
    path_count = len(merged.get("paths", {}))
    def_count = len(merged.get("definitions", {}))
    print(f"  Paths: {path_count}, Definitions: {def_count}")


if __name__ == "__main__":
    main()
