package mcmp.mc.observability.mco11ymanager.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class TumblebugSshKey {
    private List<SshKey> sshKey;

    @Getter
    @Setter
    public static class SshKey {
        private List<String> associatedObjectList;
        private String connectionName;
        private String cspSshKeyId;
        private String cspSshKeyName;
        private String description;
        private String fingerprint;
        private String id;
        private Boolean isAutoGenerated;
        private List<KeyValue> keyValueList;
        private String name;
        private String privateKey;
        private String publicKey;
        private String systemLabal;
        private String username;
        private String verifiedUsername;
    }

    @Getter
    @Setter
    public static class KeyValue {
        private String key;
        private String value;
    }
}
