package com.mcmp.o11ymanager.manager.dto.host;

import com.mcmp.o11ymanager.manager.global.annotation.Base64DecodeField;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Config 업데이트를 위한 DTO")
public class ConfigDTO {

    private String targetId;

    private String nsId;

    private String mciId;

    @Schema(description = "파일 경로", example = "telegraf.conf")
    @NotBlank
    private String path;

    @Schema(description = "Base64로 인코딩 된 설정 파일 내용", example = "W2dsb2JhbF90YWdzXQogIHV1aWQgPSAiZmZmZmZmZmYtZmZmZi1mZmZmLWZmZmYtZmZmZmZmZmZmZmZmIgogIHRhcmdldCA9ICJ2bSIKClthZ2VudF0KICBpbnRlcnZhbCA9ICI2MHMiCiAgbG9nZmlsZSA9ICIvY21wLWFnZW50L3RlbGVncmFmL2xvZy90ZWxlZ3JhZi5sb2ciCiAgcm91bmRfaW50ZXJ2YWwgPSB0cnVlCiAgbWV0cmljX2JhdGNoX3NpemUgPSAxMDAwCiAgbWV0cmljX2J1ZmZlcl9saW1pdCA9IDIwMDAwCiAgY29sbGVjdGlvbl9qaXR0ZXIgPSAiMHMiCiAgZmx1c2hfaW50ZXJ2YWwgPSAiMTBzIgogIGZsdXNoX2ppdHRlciA9ICIwcyIKICBwcmVjaXNpb24gPSAiMHMiCgpbW2lucHV0cy5jcHVdXQogIHBlcmNwdSA9IHRydWUKICB0b3RhbGNwdSA9IHRydWUKICBjb2xsZWN0X2NwdV90aW1lID0gZmFsc2UKCltbaW5wdXRzLmRpc2tdXQogIGlnbm9yZV9mcyA9IFsidG1wZnMiLCAiZGV2dG1wZnMiLCAic3F1YXNoZnMiLCAib3ZlcmxheSIsICJuc2ZzIl0KCltbaW5wdXRzLmRpc2tpb11dCgpbW2lucHV0cy5tZW1dXQoKW1tpbnB1dHMubmV0XV0KCltbaW5wdXRzLnByb2Nlc3Nlc11dCgpbW2lucHV0cy5wcm9jc3RhdF1dCiAgcHJvcGVydGllcyA9IFsiY3B1IiwgImxpbWl0cyIsICJtZW1vcnkiLCAibW1hcCJdCiAgdGFnX3dpdGggPSBbInVzZXIiXQoKW1tpbnB1dHMucHJvY3N0YXQuZmlsdGVyXV0KICBuYW1lID0gImZmZmZmZmZmLWZmZmYtZmZmZi1mZmZmLWZmZmZmZmZmZmZmZiIKCltbaW5wdXRzLnN3YXBdXQoKW1tpbnB1dHMuc3lzdGVtXV0KCltbb3V0cHV0cy5pbmZsdXhkYl1dCiB1cmxzID0gWyJodHRwOi8vMTI3LjAuMC4xOjgwODYiXQogZGF0YWJhc2UgPSAiY21wIgogdXNlcm5hbWUgPSAidGFiY2xvdWRpdCIKIHBhc3N3b3JkID0gIm15cGFzcyIKCg==")
    @Base64DecodeField
    @NotBlank
    private String content;
}
