# Build and publish mc-observability-front container image
name: CD - Front

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"
    paths:
      - "front/**"
      - ".github/workflows/deploy_front.yaml"
  workflow_dispatch:

env:
  DOCKER_REGISTRY_NAME: cloudbaristaorg
  GHCR_REGISTRY_NAME: ${{ github.repository_owner }}
  IMAGE_NAME: mc-observability-front

jobs:
  build-and-publish:
    name: Build and publish container image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{env.DOCKER_REGISTRY_NAME}}/${{env.IMAGE_NAME}}
            ghcr.io/${{env.GHCR_REGISTRY_NAME}}/${{env.IMAGE_NAME}}
          tags: |
            type=semver,enable=true,pattern={{version}}
            type=edge,enable=true,branch=main
            type=ref,event=branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-front-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-front-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
